name: gpax-multiclass
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.5.1
    - transformers==4.46.3
    - datasets
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - jax[cpu]
    - gpax
    - fsspec
    - pyarrow
    - huggingface-hub
    - tqdm
    - requests
    - ml_dtypes
    - opt_einsum
    - seaborn
