# coding=utf-8
"""Negative log likelihoods as objective functions in PyTorch."""

import torch
from GPtorch import utils
# We haven't ported GPtorch.models.gp yet, but the user plan includes models.
# For now, this function signature depends on model.apply.
# PyTorch models usually use model(params, input) or model(input) if params internal.
# Let's assume typical PyTorch module usage: model(x) returns a distribution or object with log_prob.

def objective(model, params, dataset):
  """Negative log likelihoods of model with params on datasets.

  Args:
    model: torch.nn.Module (or equivalent GP model).
    params: dictionary of parameters (if model is stateless functional) or None if stateful.
    dataset: a list of SubDataset.

  Returns:
    Negative log likelihoods of dataset generated by model defined with params.
  """
  # If params is provided, we might need to load them into model, or model supports functional call.
  # PyTorch 2.0 functional call is `torch.func.functional_call`.
  # Or we assume model is already loaded with params if params is None.
  
  # If params is passed, we try to use functional call if available, or manual parameter setting.
  # For this port, let's assume we use `torch.func.functional_call` pattern if params is not None.
  
  nll = 0.0
  for sub_dataset in dataset:
      x = sub_dataset.x
      y = sub_dataset.y
      
      if params is not None and hasattr(torch, 'func'):
          # model(x) -> distribution
          # functional_call(model, params, (x,))
          # params should be a dict of tensors matching model.named_parameters()
          
          # Note: GPax ParamsTree converts flat array to dict.
          # If params is already a dict, good.
          
          # To be safe and simple without assuming torch >= 2.0 strictly everywhere (though recommended):
          # We can implement a context manager to set params?
          # Or just assume model(x) works if params are already set.
          
          # Given the JAX signature `model.apply(params, x)`, it's explicitly functional.
          # Let's use functional_call.
          
          from torch.func import functional_call
          dist = functional_call(model, params, (x,))
      else:
          # Stateful usage
          dist = model(x)
          
      nll -= torch.sum(dist.log_prob(y))
      
  return nll

